### ISSUE TITLE
support to get list of wallets

### ISSUE THREAD

**Issue by seertenedos** [Playwo/ChiaRPC.Net#1]
Would it be possible to add the endpoint to get the list of wallets?

I am hoping to do something similar to this go class to get info on the wallets - https://github.com/retzkek/chia_exporter/blob/6e98a99913035635cc70eb9b66037fa4b684d72c/main.go#L229

**Comment by Playwo** [comment]
Yep sure, will add it later today ^^

**Comment by Playwo** [comment]
Done, on nuget very soon :)

**Comment by seertenedos** [comment]
Thanks
