### ISSUE TITLE
How do I get from an address to HexBytes?

### ISSUE THREAD

**Issue by grayfallstown** [Playwo/ChiaRPC.Net#10]
`SendTransactionAsync(uint walletId, ulong amount, ulong fee, HexBytes targetAddress)`

Obviously xch1rdeq86xprttp3wlk699jwcpa92c02u2jel2wm8f68r6s6qe9fugsyq8435 is not hex.

Am I supposed to cut off the xch prefix and turn the rest to hex?

**Comment by Playwo** [comment]
I think this is actually expecting the puzzleHash instead of the targetAddress.
I will look at the source and change it accordingly

**Comment by grayfallstown** [comment]
Then my question would be how do I get from my address to the puzzleHash?

**Comment by Playwo** [comment]
I just checked, the expected input is actually the target address.
So the parameter type is just wrong. I will push a fix in a few minutes
