### ISSUE TITLE
Implement send_transaction_multi

### ISSUE THREAD

**Issue by grayfallstown** [Playwo/ChiaRPC.Net#13]
It is not documented in the [Chia Wiki RPC API Doc](https://github.com/Chia-Network/chia-blockchain/wiki/RPC-Interfaces) but was implemented officially released with [1.2.0](https://github.com/Chia-Network/chia-blockchain/releases/tag/1.2.0)

Perfect for faucets.

**Comment by Playwo** [comment]
Done in 0.13.1
