### ISSUE TITLE
Is there a chance to get the fingerprint and first address of a wallet?

### ISSUE THREAD

**Issue by grayfallstown** [Playwo/ChiaRPC.Net#7]
Wallet ID is just an index from 1 to however many wallets you have.
I need to verify the balance of a certain fingerprint and the problem is that the index changes when a wallet gets deleted. I currently see no way to do this other can calling `wallet show` on the CLI, parsing the result and mapping the fingerprint to the index that way.

**Comment by Playwo** [comment]
How wallet show works is it logs in (`rpc log_in`) the fingerprint, then loads all wallets (`rpc get_wallets`) then just grabs the balance for each of the wallet ids returned from that (`rpc get_wallet_balance`)
Not the most elegent solution but I don't see any other way to do it that does not involve having to modify the rpc code.
